drop table if exists user_progress;
drop table if exists questions;
drop table if exists subtopics;
drop table if exists topics;

create table topics (
  id bigint generated by default as identity primary key,
  name text not null,
  slug text not null,
  icon text
);

create table subtopics (
  id bigint generated by default as identity primary key,
  topic_id bigint references topics(id),
  name text not null
);

create table questions (
  id bigint generated by default as identity primary key,
  topic_id bigint references topics(id),
  subtopic_id bigint references subtopics(id),
  question_text text not null,
  options jsonb not null,
  correct_option integer not null,
  explanation text,
  trick_tip text
);

create table user_progress (
  id bigint generated by default as identity primary key,
  user_id text not null,
  question_id bigint references questions(id),
  is_correct boolean not null,
  answered_at timestamp with time zone default timezone('utc'::text, now())
);

insert into topics (name, slug, icon) values
('Legislação', 'legislacao', '⚖️'),
('Direção Defensiva', 'direcao-defensiva', '🛡️'),
('Mecânica Básica', 'mecanica', '🔧'),
('Primeiros Socorros', 'socorros', '🚑'),
('Meio Ambiente', 'meio-ambiente', '🌳'),
('Cidadania', 'cidadania', '🤝');

insert into subtopics (topic_id, name) values
(1, 'Sinalização de Trânsito'),
(1, 'Infrações e Penalidades'),
(1, 'Processo de Habilitação'),
(2, 'Condições Adversas'),
(2, 'Tipos de Colisão'),
(2, 'Cinto de Segurança'),
(3, 'Motor e Sistemas'),
(3, 'Painel de Instrumentos'),
(4, 'Avaliação Inicial'),
(4, 'Hemorragias'),
(5, 'Poluição Veicular'),
(6, 'Convívio Social no Trânsito');

insert into questions (topic_id, subtopic_id, question_text, options, correct_option, explanation, trick_tip) values
(1, 1, 'Diante da placa R-1 (Pare), o condutor deve:', '["Reduzir a velocidade e entrar", "Parar obrigatoriamente", "Dar preferência e seguir", "Buzinar e avançar"]', 1, 'A placa R-1 impõe parada total obrigatória do veículo.', 'Não confunda com "Dê a Preferência". Pare significa imobilização total das rodas.'),
(1, 1, 'As placas de advertência têm a função de:', '["Punir o condutor", "Alertar sobre perigos na via", "Indicar distâncias", "Regulamentar proibições"]', 1, 'Placas amarelas (advertência) servem para alertar sobre condições perigosas.', 'Regulamentação é vermelho (proibição/obrigação), Advertência é amarelo (alerta).'),
(1, 2, 'Dirigir veículo segurando ou manuseando telefone celular é infração:', '["Média", "Grave", "Gravíssima", "Leve"]', 2, 'O CTB define o uso de celular como infração gravíssima.', 'Tudo que desvia muito a atenção tende a ser gravíssima.'),
(2, 4, 'O que é aquaplanagem?', '["Perda de freio na descida", "Perda de contato dos pneus com o solo devido à água", "Motor superaquecido", "Falta de visibilidade na chuva"]', 1, 'Aquaplanagem é quando o pneu flutua sobre uma camada de água.', 'Lembre-se: Aqua (água) + Planagem (planar/flutuar). Não freie bruscamente!'),
(3, 8, 'A luz vermelha com símbolo de bateria no painel indica:', '["Bateria carregada", "Problema no sistema de carga/alternador", "Falta de água", "Porta aberta"]', 1, 'Indica que o alternador não está carregando a bateria corretamente.', 'Luz vermelha no painel é sempre alerta grave. Pare o carro.');